desc: "Script for running the inferece."

model:
  name: "BERT"
  desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
  path: "../models/fernet10_nonslavic/model"

datasets:
  poner1.0:
    name: "Poner 1.0"
    desc: "Pero OCR NER 1.0 dataset"
    path: "../datasets/poner1.0"
