desc: "Script for running the inferece."

models:
  - name: "Fernet5NonSlavic"
    desc: "Fernet on 5 epochs without slavic corpus"
    path: "../models/fernet5_nonslavic/model"
  - name: "Fernet5"
    desc: "Fernet on 5 epochs with slavic corpus"
    path: "../models/fernet5/model"
  - name: "Fernet10NonSlavic"
    desc: "Fernet on 10 epochs without slavic corpus"
    path: "../models/fernet10_nonslavic/model"
  - name: "Fernet10"
    desc: "Fernet on 10 epochs with slavic corpus"
    path: "../models/fernet10/model"
  - name: "Fernet15NonSlavic"
    desc: "Fernet on 15 epochs without slavic corpus"
    path: "../models/fernet15_nonslavic/model"
  - name: "Fernet15"
    desc: "Fernet on 15 epochs with slavic corpus"
    path: "../models/fernet15/model"
  - name: "Robeczech5NonSlavic"
    desc: "Robeczech on 5 epochs without slavic corpus"
    path: "../models/robeczech5_nonslavic/model"
  - name: "Robeczech5"
    desc: "Robeczech on 5 epochs with slavic corpus"
    path: "../models/robeczech5/model"
  - name: "Robeczech10NonSlavic"
    desc: "Robeczech on 10 epochs without slavic corpus"
    path: "../models/robeczech10_nonslavic/model"
  - name: "Robeczech10"
    desc: "Robeczech on 10 epochs with slavic corpus"
    path: "../models/robeczech10/model"
  - name: "Robeczech15NonSlavic"
    desc: "Robeczech on 15 epochs without slavic corpus"
    path: "../models/robeczech15_nonslavic/model"
  - name: "Robeczech15"
    desc: "Robeczech on 15 epochs with slavic corpus"
    path: "../models/robeczech15/model"
  - name: "XmlRobertaBase5NonSlavic"
    desc: "XmlRobertaBase on 5 epochs without slavic corpus"
    path: "../models/xmlrobertabase5_nonslavic/model"
  - name: "XmlRobertaBase5"
    desc: "XmlRobertaBase on 5 epochs with slavic corpus"
    path: "../models/xmlrobertabase5/model"
  - name: "XmlRobertaBase10NonSlavic"
    desc: "XmlRobertaBase on 10 epochs without slavic corpus"
    path: "../models/xmlrobertabase10_nonslavic/model"
  - name: "XmlRobertaBase10"
    desc: "XmlRobertaBase on 10 epochs with slavic corpus"
    path: "../models/xmlrobertabase10/model"
  - name: "XmlRobertaBase15NonSlavic"
    desc: "XmlRobertaBase on 15 epochs without slavic corpus"
    path: "../models/xmlrobertabase15_nonslavic/model"
  - name: "XmlRobertaBase15"
    desc: "XmlRobertaBase on 15 epochs with slavic corpus"
    path: "../models/xmlrobertabase15/model"

datasets:
  poner1.0:
    name: "Poner 1.0"
    desc: "Pero OCR NER 1.0 dataset"
    path: "../datasets/poner1.0"
