desc: "Script for running the inferece."

models:
  model1:
    name: "BERT"
    desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
    path: "../models/robeczech_5_epochs-3h/model/"
  model2:
    name: "BERT"
    desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
    path: "../models/robeczech_10_epochs-3h/model/"
  model3:
    name: "BERT"
    desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
    path: "../models/robeczech_15_epochs-3h/model/"

raw_text:
  pero:
    name: "Pero"
    desc: "Czech Named Entity Corpus 2.0 CoNNL dataset. General-language Czech NER dataset."
    path: "../raw_text/2023-11-23/"
