desc: "Script for running the inferece."

models:
  model1:
    name: "Robeczech"
    desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
    path: "../models/robeczech15_nonslavic/model/"
  model2:
    name: "Fernet"
    desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
    path: "../models/fernet15_nonslavic/model/"
  model3:
    name: "xmlRobertaBase"
    desc: "BERT - Model-BiDirectional Encoder Decoder Transformer"
    path: "../models/xmlrobertabase15_nonslavic/model/"

datasets:
  poner1.0:
    name: "Poner 1.0"
    desc: "Pero OCR NER 1.0 dataset"
    path: "../datasets/poner1.0"
