desc: "Script for running the inferece."

models:
  model1:
    name: "Fernet"
    desc: "Fine-tuned fernet model with fernetc5_15_epochs_noslavic configuration"
    path: "../models/fernet15_nonslavic/model/"
  model2:
    name: "Robeczech"
    desc: "Fine-tuned robeczech model with robeczech_15_epochs_noslavic configuration"
    path: "../models/robeczech15_noslavic/model/"
  model3:
    name: "Xmlrobertabase"
    desc: "Fine-tuned xmlrobertabase model with xmlrobertabase_15_epochs_noslavic configuration"
    path: "../models/xmlrobertabase15_nonslavic/model/"

raw_text:
  pero:
    name: "Pero"
    desc: "Text from pero OCR"
    path: "../raw_text/2023-11-23_/"
