desc: "Baseline experiment. Learning rate scheduler is linear, training 5 epochs on CNEC2 dataset."

model:
  name: "robeczech-base"
  desc: "ufal - robeczech-base"
  path: "ufal/robeczech-base"

datasets:
  cnec2:
    name: "medival"
    desc: "medival"
    path: "../datasets/medival"

training:
  num_train_epochs: 10
  batch_size: 16

  optimizer:
    learning_rate: 3.e-5
    weight_decay: 0.
    beta1: 0.9
    beta2: 0.999
  lr_scheduler:
    name: "linear"
    num_warmup_steps: 0.06
